apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
    name: hugepages-allocator
    namespace: kube-system
spec:
  template:
    metadata:
      labels:
        name: hugepages-allocator
    spec:
      containers:
      - image: derekwaynecarr/hugepages-allocator:v0.1
        command: ["/bin/sh", "-c"]
        args: ["usr/bin/hugepages-allocator.sh && sleep infinity"]
        env:
          - name: NR_HUGEPAGES
            value: "512"
        name: hugepages-allocator
        resources:
          requests:
            cpu: 0.15
        securityContext:
          privileged: true